CREATE TABLE DATA_VIGENCIA (
    DVG_ID    INTEGER NOT NULL,
    DVG_DT_INICIO  DATE NOT NULL,
    DVG_DT_FIM     DATE NOT NULL,
    CONSTRAINT PK_DATA_VIGENCIA PRIMARY KEY (DVG_ID),
    CONSTRAINT UK_DATA_VIGENCIA UNIQUE (DVG_DT_INICIO, DVG_DT_FIM)
);

CREATE SEQUENCE SEQ_DATA_VIGENCIA;
