CREATE TABLE HORARIOS (
    HOR_CODIGO       INTEGER NOT NULL,
    HOR_DESCRICAO    VARCHAR(200) NOT NULL,
    HOR_QTD_AULA     INTEGER DEFAULT 1 NOT NULL,
    HOR_ORDEM_AULA   INTEGER DEFAULT 1 NOT NULL,
    HOR_HORA_INICIO  TIME DEFAULT CURRENT_TIME NOT NULL,
    HOR_HORA_FIM     TIME DEFAULT CURRENT_TIME NOT NULL,
    HOR_DURACAO      TIME NOT NULL,
    CONSTRAINT PK_HORARIOS PRIMARY KEY (HOR_CODIGO)
);

CREATE SEQUENCE SEQ_HORARIOS;
