CREATE TABLE GRADE_CURRICULAR (
    GRC_ID                   INTEGER NOT NULL,
    GRC_CURSO                INTEGER NOT NULL,
    GRC_DISCIPLINA           INTEGER NOT NULL,
    GRC_SERIE                INTEGER NOT NULL,
    GRC_DATAVIGENCIA         INTEGER NOT NULL,
    GRC_CARGAHORARIATOTAL    INTEGER NOT NULL,
    GRC_CARGAHORARIASEMANAL  INTEGER NOT NULL,
    CONSTRAINT PK_GRADECURRICULAR PRIMARY KEY (GRC_ID),
    CONSTRAINT FK_GRADECURRICULAR_CURSOS FOREIGN KEY (GRC_CURSO) REFERENCES CURSOS (CUR_CODIGO),
    CONSTRAINT FK_GRADECURRICULAR_DISCIPLINA FOREIGN KEY (GRC_DISCIPLINA) REFERENCES DISCIPLINAS (DIS_CODIGO),
    CONSTRAINT FK_GRADECURRICULAR_SERIE FOREIGN KEY (GRC_SERIE) REFERENCES SERIES (SER_ANO),
    CONSTRAINT FK_GRADECURRICULAR_DTVIGENCIA FOREIGN KEY (GRC_DATAVIGENCIA) REFERENCES DATA_VIGENCIA (DVG_ID),
    CONSTRAINT UK_GRADECURRICULAR UNIQUE (GRC_CURSO, GRC_DISCIPLINA, GRC_DATAVIGENCIA)
);

CREATE SEQUENCE SEQ_GRADE_CURRICULAR;

