CREATE TABLE CURSOS(
  CUR_CODIGO INTEGER NOT NULL,
  CUR_NOME VARCHAR(200) NOT NULL,
  CUR_DURACAO integer NOT NULL,
  CUR_TIPO_DURACAO VARCHAR(1) DEFAULT 'A' NOT NULL,  /*SEMESTRAL, MENSAL, ANUAL*/
  CUR_PERIODO VARCHAR(1) DEFAULT 'N' NOT NULL, /*N - NOTURNO*/
  CUR_NIVEL VARCHAR(1) DEFAULT 'G' NOT NULL, /*GRADUACAO, POS-GRADUACAO*/
  CUR_DEPARTAMENTO INTEGER NOT NULL,
  CONSTRAINT PK_CURSOS PRIMARY KEY (CUR_CODIGO),
  CONSTRAINT FK_CURSOS_DEPARTAMENTOS FOREIGN KEY (CUR_DEPARTAMENTO) REFERENCES DEPARTAMENTOS (DEP_CODIGO);
);

CREATE SEQUENCE SEQ_CURSOS;
