insert into PESSOAS (PES_CODIGO, PES_CPFCNPJ, PES_TIPO, PES_GENERO, PES_DATANASCIMENTO, PES_TIPOPESSOA,
                     PES_NOMECOMPLETO)
values (1, '111.111.111-11', 'PRO', 'M', '1-JAN-1990', 'F', 'JOSE DA SILVA');

insert into PESSOAS (PES_CODIGO, PES_CPFCNPJ, PES_TIPO, PES_GENERO, PES_DATANASCIMENTO, PES_TIPOPESSOA,
                     PES_NOMECOMPLETO)
values (2, '222.222.222-22', 'PRO', 'F', '1-JAN-1990', 'F', 'CECILIA EMACULADA');

insert into PESSOAS (PES_CODIGO, PES_CPFCNPJ, PES_TIPO, PES_GENERO, PES_DATANASCIMENTO, PES_TIPOPESSOA,
                     PES_NOMECOMPLETO)
values (3, '333.333.333-33', 'PRO', 'M', '1-JAN-1990', 'F', 'MATHEUS SANTOS');

insert into PESSOAS (PES_CODIGO, PES_CPFCNPJ, PES_TIPO, PES_GENERO, PES_DATANASCIMENTO, PES_TIPOPESSOA,
                     PES_NOMECOMPLETO)
values (4, '444.444.444-44', 'PRO', 'F', '1-JAN-1990', 'F', 'JOAQUINA DA SILVA');

insert into PESSOAS (PES_CODIGO, PES_CPFCNPJ, PES_TIPO, PES_GENERO, PES_DATANASCIMENTO, PES_TIPOPESSOA,
                     PES_NOMECOMPLETO)
values (5, '555.555.555-55', 'PRO', 'M', '1-JAN-1990', 'F', 'RAFAEL DA SILVA');

insert into PESSOAS (PES_CODIGO, PES_CPFCNPJ, PES_TIPO, PES_GENERO, PES_DATANASCIMENTO, PES_TIPOPESSOA,
                     PES_NOMECOMPLETO)
values (6, '666.666.666-66', 'PRO', 'M', '1-JAN-1990', 'F', 'PAULO MUNHOZ DOS SANTOS');

insert into PESSOAS (PES_CODIGO, PES_CPFCNPJ, PES_TIPO, PES_GENERO, PES_DATANASCIMENTO, PES_TIPOPESSOA,
                     PES_NOMECOMPLETO)
values (7, '777.777.777-77', 'PRO', 'F', '1-JAN-1990', 'F', 'MARIA DA SILVA');

insert into PESSOAS (PES_CODIGO, PES_CPFCNPJ, PES_TIPO, PES_GENERO, PES_DATANASCIMENTO, PES_TIPOPESSOA,
                     PES_NOMECOMPLETO)
values (8, '888.888.888-88', 'PRO', 'F', '1-JAN-1990', 'F', 'FERNANDA SANTOS');

insert into PESSOAS (PES_CODIGO, PES_CPFCNPJ, PES_TIPO, PES_GENERO, PES_DATANASCIMENTO, PES_TIPOPESSOA,
                     PES_NOMECOMPLETO)
values (9, '999.999.999-99', 'PRO', 'F', '1-JAN-1990', 'F', 'ROBERTA MORAIS');


