INSERT INTO DEPARTAMENTOS (DEP_CODIGO, DEP_DESCRICAO)
                   VALUES (1, 'ADMINISTRACAO');
INSERT INTO DEPARTAMENTOS (DEP_CODIGO, DEP_DESCRICAO)
                   VALUES (2, 'INFORMATICA');
INSERT INTO DEPARTAMENTOS (DEP_CODIGO, DEP_DESCRICAO)
                   VALUES (3, 'CIENCIAS CONTABEIS');
INSERT INTO DEPARTAMENTOS (DEP_CODIGO, DEP_DESCRICAO)
                   VALUES (4, 'DIREITO');
INSERT INTO DEPARTAMENTOS (DEP_CODIGO, DEP_DESCRICAO)
                   VALUES (5, 'EDUCACAO FISICA');
INSERT INTO DEPARTAMENTOS (DEP_CODIGO, DEP_DESCRICAO)
                   VALUES (6, 'ENFERMAGEM');
INSERT INTO DEPARTAMENTOS (DEP_CODIGO, DEP_DESCRICAO)
                   VALUES (7, 'TECNOLOGIA EM RECURSOS HUMANOS');
INSERT INTO DEPARTAMENTOS (DEP_CODIGO, DEP_DESCRICAO)
                   VALUES (8, 'HISTORIA');
INSERT INTO DEPARTAMENTOS (DEP_CODIGO, DEP_DESCRICAO)
                   VALUES (9, 'LETRAS');
INSERT INTO DEPARTAMENTOS (DEP_CODIGO, DEP_DESCRICAO)
                   VALUES (10, 'PEDAGOGIA');

COMMIT WORK;
