INSERT INTO DEPARTAMENTOS (DEP_CODIGO, DEP_DESCRICAO)
                   VALUES (1, 'ADMINISTRAÇÃO');
INSERT INTO DEPARTAMENTOS (DEP_CODIGO, DEP_DESCRICAO)
                   VALUES (2, 'CIÊNCIA DA COMPUTAÇÃO');
INSERT INTO DEPARTAMENTOS (DEP_CODIGO, DEP_DESCRICAO)
                   VALUES (3, 'CIÊNCIAS CONTÁBEIS');
INSERT INTO DEPARTAMENTOS (DEP_CODIGO, DEP_DESCRICAO)
                   VALUES (4, 'DIREITO');
INSERT INTO DEPARTAMENTOS (DEP_CODIGO, DEP_DESCRICAO)
                   VALUES (5, 'EDUCAÇÃO FÍSICA');
INSERT INTO DEPARTAMENTOS (DEP_CODIGO, DEP_DESCRICAO)
                   VALUES (6, 'ENFERMAGEM');
INSERT INTO DEPARTAMENTOS (DEP_CODIGO, DEP_DESCRICAO)
                   VALUES (7, 'TECNOLOGIA EM RECURSOS HUMANOS');
INSERT INTO DEPARTAMENTOS (DEP_CODIGO, DEP_DESCRICAO)
                   VALUES (8, 'HISTÓRIA');
INSERT INTO DEPARTAMENTOS (DEP_CODIGO, DEP_DESCRICAO)
                   VALUES (9, 'LETRAS');
INSERT INTO DEPARTAMENTOS (DEP_CODIGO, DEP_DESCRICAO)
                   VALUES (10, 'PEDAGOGIA');

COMMIT WORK;
