INSERT INTO CURSOS (CUR_CODIGO, CUR_NOME, CUR_DURACAO, CUR_TIPO_DURACAO, CUR_PERIODO, CUR_NIVEL, CUR_CARGAHORARIA, CUR_DEPARTAMENTO)
            VALUES (1, 'ADMINISTRACAO', 4, 'A', 'N', 'G', 3140, 1);
INSERT INTO CURSOS (CUR_CODIGO, CUR_NOME, CUR_DURACAO, CUR_TIPO_DURACAO, CUR_PERIODO, CUR_NIVEL, CUR_CARGAHORARIA, CUR_DEPARTAMENTO)
            VALUES (2, 'CIENCIA DA COMPUTACAO', 4, 'A', 'N', 'G', 3280, 2);

COMMIT WORK;
