INSERT INTO DISCIPLINAS (DIS_CODIGO, DIS_DESCRICAO)
                 VALUES (1, 'MATEMATICA DISCRETA');
INSERT INTO DISCIPLINAS (DIS_CODIGO, DIS_DESCRICAO)
                 VALUES (2, 'BANCO DE DADOS');
INSERT INTO DISCIPLINAS (DIS_CODIGO, DIS_DESCRICAO)
                 VALUES (3, 'PROGRAMACAO ORIENTADO A OBJETO');
INSERT INTO DISCIPLINAS (DIS_CODIGO, DIS_DESCRICAO)
                 VALUES (4, 'CONTABILIDADE GERAL');
INSERT INTO DISCIPLINAS (DIS_CODIGO, DIS_DESCRICAO)
                 VALUES (5, 'FUNDAMENTOS DA ADMINISTRACAO');

COMMIT WORK;
