INSERT INTO GRADE_CURRICULAR (GRC_ID, GRC_CURSO, GRC_DISCIPLINA, GRC_SERIE, GRC_DATAVIGENCIA, GRC_CARGAHORARIATOTAL, GRC_CARGAHORARIASEMANAL)
                      VALUES (1, 2, 1, 1, 1, 100, 20);
INSERT INTO GRADE_CURRICULAR (GRC_ID, GRC_CURSO, GRC_DISCIPLINA, GRC_SERIE, GRC_DATAVIGENCIA, GRC_CARGAHORARIATOTAL, GRC_CARGAHORARIASEMANAL)
                      VALUES (2, 2, 2, 1, 1, 200, 100);

COMMIT WORK;
