insert into PROFESSOR_HORARIO (PFH_CURSO, PFH_DISCIPLINA, PFH_SERIE, PFH_PROFESSOR, PFH_HORARIO, PFH_ANOLETIVO,
                               PFH_DIADASEMANA)
values (2, 2, 2, '333.333.333-33', 1, 2019, 2);

insert into PROFESSOR_HORARIO (PFH_CURSO, PFH_DISCIPLINA, PFH_SERIE, PFH_PROFESSOR, PFH_HORARIO, PFH_ANOLETIVO,
                               PFH_DIADASEMANA)
values (2, 2, 2, '333.333.333-33', 2, 2019, 2);

insert into PROFESSOR_HORARIO (PFH_CURSO, PFH_DISCIPLINA, PFH_SERIE, PFH_PROFESSOR, PFH_HORARIO, PFH_ANOLETIVO,
                               PFH_DIADASEMANA)
values (2, 2, 2, '333.333.333-33', 3, 2019, 3);

insert into PROFESSOR_HORARIO (PFH_CURSO, PFH_DISCIPLINA, PFH_SERIE, PFH_PROFESSOR, PFH_HORARIO, PFH_ANOLETIVO,
                               PFH_DIADASEMANA)
values (2, 2, 2, '333.333.333-33', 4, 2019, 3);

insert into PROFESSOR_HORARIO (PFH_CURSO, PFH_DISCIPLINA, PFH_SERIE, PFH_PROFESSOR, PFH_HORARIO, PFH_ANOLETIVO,
                               PFH_DIADASEMANA)
values (2, 1, 1, '333.333.333-33', 3, 2019, 2);

insert into PROFESSOR_HORARIO (PFH_CURSO, PFH_DISCIPLINA, PFH_SERIE, PFH_PROFESSOR, PFH_HORARIO, PFH_ANOLETIVO,
                               PFH_DIADASEMANA)
values (2, 1, 1, '333.333.333-33', 4, 2019, 2);

insert into PROFESSOR_HORARIO (PFH_CURSO, PFH_DISCIPLINA, PFH_SERIE, PFH_PROFESSOR, PFH_HORARIO, PFH_ANOLETIVO,
                               PFH_DIADASEMANA)
values (2, 1, 1, '333.333.333-33', 1, 2019, 3);

insert into PROFESSOR_HORARIO (PFH_CURSO, PFH_DISCIPLINA, PFH_SERIE, PFH_PROFESSOR, PFH_HORARIO, PFH_ANOLETIVO,
                               PFH_DIADASEMANA)
values (2, 1, 1, '333.333.333-33', 2, 2019, 3);
