INSERT INTO SERIES (SER_ANO, SER_DESCRICAO)
            VALUES (1, '1º ANO');
INSERT INTO SERIES (SER_ANO, SER_DESCRICAO)
            VALUES (2, '2º ANO');
INSERT INTO SERIES (SER_ANO, SER_DESCRICAO)
            VALUES (3, '3º ANO');
INSERT INTO SERIES (SER_ANO, SER_DESCRICAO)
            VALUES (4, '4º ANO');
INSERT INTO SERIES (SER_ANO, SER_DESCRICAO)
            VALUES (5, '5º ANO');
INSERT INTO SERIES (SER_ANO, SER_DESCRICAO)
            VALUES (6, '6º ANO');
INSERT INTO SERIES (SER_ANO, SER_DESCRICAO)
            VALUES (7, '7º ANO');
INSERT INTO SERIES (SER_ANO, SER_DESCRICAO)
            VALUES (8, '8º ANO');
INSERT INTO SERIES (SER_ANO, SER_DESCRICAO)
            VALUES (9, '9º ANO');
INSERT INTO SERIES (SER_ANO, SER_DESCRICAO)
            VALUES (10, '10º ANO');

COMMIT WORK;
